/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import DAO.PratoDAO;
import classes.Prato;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author garot
 */
public class FrmPrato extends javax.swing.JFrame {

    /**
     * Creates new form frmPratos
     */
    public FrmPrato() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnInserirPrato = new javax.swing.JButton();
        btnEditarPrato = new javax.swing.JButton();
        btnListarPrato = new javax.swing.JButton();
        btnExcluirPrato = new javax.swing.JButton();
        btnVoltarDoPrato = new javax.swing.JButton();
        btnPesquisarPrato = new javax.swing.JButton();
        txtPesquisarPrato = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNomePrato = new javax.swing.JTextField();
        txtCategoriaPrato = new javax.swing.JTextField();
        txtPrecoPrato = new javax.swing.JTextField();
        txtDescricaoPrato = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePratos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu dos Pratos");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 30)); // NOI18N
        jLabel1.setText("Pratos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Escolha uma opção:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        btnInserirPrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/1NOVO.png"))); // NOI18N
        btnInserirPrato.setText("Cadastrar");
        btnInserirPrato.setToolTipText("");
        btnInserirPrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirPratoActionPerformed(evt);
            }
        });

        btnEditarPrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/3EDITAR.png"))); // NOI18N
        btnEditarPrato.setText("Editar");
        btnEditarPrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPratoActionPerformed(evt);
            }
        });

        btnListarPrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/2LISTAR.png"))); // NOI18N
        btnListarPrato.setText("Listar");
        btnListarPrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarPratoActionPerformed(evt);
            }
        });

        btnExcluirPrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/4EXCLUIR.png"))); // NOI18N
        btnExcluirPrato.setText("Excluir");
        btnExcluirPrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirPratoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(btnInserirPrato)
                .addGap(67, 67, 67)
                .addComponent(btnListarPrato, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnEditarPrato, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnExcluirPrato, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListarPrato, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(btnInserirPrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarPrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluirPrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnVoltarDoPrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/voltar.png"))); // NOI18N
        btnVoltarDoPrato.setText("Voltar");
        btnVoltarDoPrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarDoPratoActionPerformed(evt);
            }
        });

        btnPesquisarPrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/7PESQUISAR.png"))); // NOI18N
        btnPesquisarPrato.setText("Pesquisar");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações do Prato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Categoria:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Preço:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Descrição:");

        txtCategoriaPrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoriaPratoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(107, 107, 107)
                        .addComponent(txtNomePrato))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCategoriaPrato)
                            .addComponent(txtPrecoPrato)
                            .addComponent(txtDescricaoPrato, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE))))
                .addGap(78, 78, 78))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomePrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCategoriaPrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrecoPrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDescricaoPrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jTablePratos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Título 5", "Título 6"
            }
        ));
        jScrollPane1.setViewportView(jTablePratos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(461, 461, 461)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnVoltarDoPrato)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPesquisarPrato)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisarPrato, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarPrato, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarPrato, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnVoltarDoPrato)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>                        

    private void btnVoltarDoPratoActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        new FrmRestaurante().setVisible(true);
        this.dispose();
    }                                                

    private void btnInserirPratoActionPerformed(java.awt.event.ActionEvent evt) {                                                
        try {
          
           String nome = txtNomePrato.getText();
           String categoria = txtCategoriaPrato.getText();
           String precoStr = txtPrecoPrato.getText();
           String descricao = txtDescricaoPrato.getText();
           
           if(nome.isEmpty() || categoria.isEmpty() || precoStr.isEmpty()){
                JOptionPane.showMessageDialog(this, "Preencha todos os campos do Formulario");
                return;
            }
            
            double preco = Double.parseDouble(precoStr);
           
            Prato prato = new Prato();
            prato.setNome(nome);
            prato.setCategoria(categoria);
            prato.setPreco(preco);
            prato.setDescricao(descricao);
            prato.setDisp(true);
            
            PratoDAO dao = new PratoDAO();
            dao.adicionarPrato(prato);
          
            JOptionPane.showMessageDialog(this,"Prato adicionado com Sucesso!");
            limparCampos();
            
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Preço inválido!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao adicionar prato: " + e.getMessage());
    }
    }                                               

    private void txtCategoriaPratoActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void btnEditarPratoActionPerformed(java.awt.event.ActionEvent evt) {                                               
      try {
      
          String idStr = JOptionPane.showInputDialog(this, "Qual o id do Produto que você que editar: ");
            if(idStr == null || idStr.trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "Id não encontrado ou operação cancelada!");
                return;
            }
          
           int codigo = Integer.parseInt(idStr.trim());
           PratoDAO dao = new PratoDAO();
           Prato prato = dao.pesquisarPrato(codigo);

        if (prato == null) {
            JOptionPane.showMessageDialog(this, "Prato não encontrado!");
            return;
        }

            String nome = txtNomePrato.getText();
            String categoria = txtCategoriaPrato.getText();
            String precoStr = txtPrecoPrato.getText();
            String descricao = txtDescricaoPrato.getText();
            
            
            if(nome.isEmpty() || categoria.isEmpty() || precoStr.isEmpty()){
                JOptionPane.showMessageDialog(this, "Preencha todos os campos do Formulario");
            }
            
            double preco = Double.parseDouble(precoStr);
            
             
            prato.setCodigo(codigo); 
            prato.setNome(nome);
            prato.setCategoria(categoria);
            prato.setPreco(preco);
            prato.setDescricao(descricao);
            prato.setDisp(true);
           
            dao.atualizarPrato(prato);
             
            JOptionPane.showMessageDialog(this,"Prato atualizado com sucesso!");
            limparCampos();
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Preço invalido!");
        }catch(Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao atualizar prato: " + e.getMessage());
    }
    }                                              

    private void btnExcluirPratoActionPerformed(java.awt.event.ActionEvent evt) {                                                
         try {
        String id = JOptionPane.showInputDialog(this, "Digite o ID do prato que deseja excluir:\n");
        if (id == null || id.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Operação cancelada ou ID não informado.");
            return;
        }

        int codigo = Integer.parseInt(id.trim());
        PratoDAO dao = new PratoDAO();
        Prato prato = dao.pesquisarPrato(codigo);

        if (prato == null) {
            JOptionPane.showMessageDialog(this, "Prato não encontrado!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, 
            "Tem certeza que deseja excluir o prato de ID " + codigo + "?", 
            "Confirmação", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        dao.deletarPrato(codigo);
        JOptionPane.showMessageDialog(this, "Prato excluído com sucesso!");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, digite um número válido para o ID.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao excluir prato: " + e.getMessage());
    }
    }                                               

    private void btnListarPratoActionPerformed(java.awt.event.ActionEvent evt) {                                               
         try {
             
        PratoDAO dao = new PratoDAO();
        List<Prato> pratos = dao.listarPrato();
        if(pratos == null || pratos.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nenhum Pedido encontrado!");
            return;
        }
        StringBuilder sb = new StringBuilder();
        
        for (Prato p : pratos) {
            sb.append(p.toString()).append("\n----------------\n");
        }
        
        
        JOptionPane.showMessageDialog(this, sb.length() > 0 ? sb.toString() : "Nenhum prato encontrado.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao listar pratos: " + e.getMessage());
    }
    }                                              
    
    private void limparCampos() {
        txtNomePrato.setText("");
        txtCategoriaPrato.setText("");
        txtPrecoPrato.setText("");
        txtDescricaoPrato.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrato().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnEditarPrato;
    private javax.swing.JButton btnExcluirPrato;
    private javax.swing.JButton btnInserirPrato;
    private javax.swing.JButton btnListarPrato;
    private javax.swing.JButton btnPesquisarPrato;
    private javax.swing.JButton btnVoltarDoPrato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePratos;
    private javax.swing.JTextField txtCategoriaPrato;
    private javax.swing.JTextField txtDescricaoPrato;
    private javax.swing.JTextField txtNomePrato;
    private javax.swing.JTextField txtPesquisarPrato;
    private javax.swing.JTextField txtPrecoPrato;
    // End of variables declaration                   
}
