CREATE DATABASE BD_Restaurante;
GO

CREATE TABLE tbPrato (
    PRA_CODIGO INT IDENTITY PRIMARY KEY,
    PRA_NOME VARCHAR(100) NOT NULL,
    PRA_CATEGORIA VARCHAR(50),
    PRA_PRECO DECIMAL(10,2) NOT NULL,
    PRA_DISPONIBILIDADE BIT DEFAULT 1,
    PRA_DESCRICAO VARCHAR(255)
);
GO

CREATE TABLE tbPedido (
    PED_CODIGO INT IDENTITY PRIMARY KEY,
    PRA_CODIGO INT NOT NULL,
    PED_CLIENTE VARCHAR(100) NOT NULL,
    PED_QTDE INT NOT NULL,
    PED_DATA DATETIME DEFAULT GETDATE(),
    PED_STATUS VARCHAR(50),

    FOREIGN KEY (PRA_CODIGO) REFERENCES tbPrato(PRA_CODIGO)
);
GO

